export const copy = {
  en: {
    langName: "English",
    product: "Free Care",
    tagline: "A brick board for Nevada help — not an app that pays anyone.",
    banner:
      "Not Medicaid. Not an ISO. Not a fiscal intermediary. We never collect names, SSNs, or Medicaid IDs. We cannot enroll you, pay a caregiver, or file with the state.",
    boardKicker: "Las Vegas · Clark County · Nevada",
    boardTitle: "The brick board",
    boardLead:
      "Four large bricks. Tap one. Each brick only points you at official Nevada doors — ACCESS Nevada, DHCFP, 211, Clark County cooling — and tells you what those programs actually are.",
    brick1: "Can Nevada pay for this care?",
    brick1sub: "Wizard · bilingual · no determination",
    brick2: "Document pack",
    brick2sub: "Checklists · official forms · you file",
    brick3: "Who is real vs a scam",
    brick3sub: "Official doors · red flags",
    brick4: "Heat & missed visit",
    brick4sub: "Stay Cool · 311 · 211",
    mini211: "Nevada 211",
    miniAccess: "ACCESS Nevada",
    miniDhcpf: "DHCFP PCS",
    miniCool: "Stay Cool Clark",
    navBoard: "Board",
    navWizard: "Wizard",
    navPack: "Pack",
    navDirectory: "Directory",
    navHeat: "Heat",
    navLegal: "Legal",
    footerLegal: "Legal / what this is not",
    wizardTitle: "Can Nevada pay for this care?",
    wizardLead:
      "This is a signpost, not an eligibility decision. Answer in your own words. Nothing is uploaded. Nobody at Medicaid sees this screen.",
    stepWhere: "Where is the person who needs help?",
    whereVegas: "Las Vegas / Clark County",
    whereNv: "Somewhere else in Nevada",
    whereOut: "Not in Nevada",
    stepMedicaid: "Do they already have Nevada Medicaid?",
    medYes: "Yes",
    medNo: "No / I don’t think so",
    medUnsure: "Not sure",
    stepNeed: "What kind of help is needed at home? (check any)",
    needBath: "Bathing or dressing",
    needToilet: "Toileting or incontinence",
    needMeal: "Meals or feeding",
    needMove: "Getting in/out of bed or a chair",
    needMeds: "Cueing medications (not nursing)",
    needNone: "Mostly companionship / errands only",
    stepWho: "Who would be the paid caregiver, if anyone?",
    whoSelf: "The person themselves (no paid aide)",
    whoSpouse: "Spouse / domestic partner",
    whoParentMinor: "Parent of a child under 18",
    whoGuardian: "Legal guardian of the person",
    whoAdultChild: "Adult child, sibling, or other relative (not spouse/guardian)",
    whoFriend: "Friend / neighbor / non-relative",
    whoAgency: "A licensed agency would send staff",
    whoUnsure: "Not sure yet",
    next: "Next brick",
    back: "Back",
    restart: "Start over",
    resultTitle: "What the public rules point toward",
    resultNotAdvice: "This is not a determination. A caseworker at ACCESS Nevada or DHCFP has to say yes or no.",
    pathAccessTitle: "Door 1 — apply or check Medicaid",
    pathAccessBody:
      "Nevada Medicaid (including MAABD for many older adults and people with disabilities) is the usual on-ramp to Personal Care Services. Apply or check status only at ACCESS Nevada. Paper packets mail to DSS, PO Box 15400, Las Vegas, NV 89114.",
    pathPcsTitle: "Door 2 — Personal Care Services (PCS)",
    pathPcsBody:
      "If they already have Nevada Medicaid, a physician or other allowed source can request a PCS assessment. DHCFP’s public number for that request is 800-525-2395. Nevada PCS can be agency-based or self-directed through a licensed Intermediary Service Organization — not through this site.",
    pathCannotPayTitle: "Hard stop — this person probably cannot be the paid aide",
    pathCannotPayBody:
      "Nevada Medicaid Personal Care Services generally does not pay a legally responsible individual: a spouse, a legal guardian, or a parent of a minor recipient. Adult children of adult recipients and many other relatives often can be hired in the self-directed model — that decision is the ISO’s and DHCFP’s, not ours.",
    pathOutTitle: "This board is built for Nevada",
    companionOnly:
      "Companionship and errands alone usually are not Personal Care Services. PCS is built around bathing, dressing, toileting, meals, and transfers — a caseworker still has to decide.",
    pathOutBody:
      "Other states have different Medicaid personal-care rules (New York CDPAP is not Nevada PCS). Start with that state’s official Medicaid portal, not this board.",
    path211Title: "Always — Nevada 211 and ADSD",
    path211Body:
      "Even without Medicaid, 211 can route meals, caregiver respite leads, and aging services. Aging and Disability Services (ADSD) is the state aging network — not a fiscal intermediary.",
    openAccess: "Open ACCESS Nevada",
    openApply: "How to apply (DSS)",
    openPcs: "Open DHCFP PCS page",
    open211: "Open Nevada 211 seniors",
    callPcs: "PCS assessment request",
    callDss: "DWSS / Medicaid help line",
    callVegas: "Las Vegas Medicaid district",
    packTitle: "Document pack",
    packLead:
      "A local checklist only. We do not store your papers, fill PDF fields, or submit anything to Nevada. Print or screenshot this list. File with ACCESS Nevada yourself.",
    packMaabd: "Usually needed for MAABD / aged-blind-disabled Medicaid",
    packPcs: "Usually needed later for Personal Care Services",
    packDone: "Packed",
    packOpen: "Official page",
    resetChecks: "Clear local checks",
    dirTitle: "Who is real vs a scam",
    dirLead:
      "Only use the doors Nevada actually publishes. We do not list private agencies or “licenses” we cannot verify from this computer. If someone cold-calls asking for your SSN to “enroll you in Medicaid,” hang up.",
    dirOfficial: "Official doors",
    dirFlags: "Red flags — walk away",
    dirCall: "Call",
    heatTitle: "Heat and a missed visit",
    heatLead:
      "This is a safety card, not a medical record and not an EVV clock. No diagnoses, no medication lists, no proof a caregiver showed up.",
    heatStayCool: "Clark County Stay Cool",
    heat311: "Clark County 211 / 311 style help",
    heatIfMissed: "If a caregiver did not show up",
    heatIfMissedBody:
      "Call the agency or ISO that employs them. If the person is in immediate danger from heat, call 911. For non-emergency cooling and senior help, use Stay Cool and Nevada 211. Confirm cooling-center hours the day you go — they change.",
    heatCenters: "Cooling places people mention (confirm hours)",
    confirmHours: "Confirm hours before you go",
    legalTitle: "What Free Care is not",
    legalBody:
      "Free Care is a public navigator for people in Clark County and the rest of Nevada. It is not FreedomCare, not a licensed Intermediary Service Organization, not a fiscal intermediary, not Medicaid, and not an employer. Instant caregiver pay, EVV, and timesheets belong to licensed agencies and ISOs after the state says someone is eligible — never to this brick board.",
  },
  es: {
    langName: "Español",
    product: "Free Care",
    tagline: "Un tablero de ladrillos para ayuda en Nevada — no es una app que le paga a nadie.",
    banner:
      "No es Medicaid. No es un ISO. No es un intermediario fiscal. Nunca pedimos nombres, SSN ni números de Medicaid. No podemos inscribirle, pagarle a un cuidador ni presentar papeles al estado.",
    boardKicker: "Las Vegas · Condado Clark · Nevada",
    boardTitle: "El tablero de ladrillos",
    boardLead:
      "Cuatro ladrillos grandes. Toque uno. Cada ladrillo solo lo lleva a puertas oficiales de Nevada — ACCESS Nevada, DHCFP, 211, calor del condado — y dice qué son esos programas de verdad.",
    brick1: "¿Puede Nevada pagar este cuidado?",
    brick1sub: "Asistente · bilingüe · no es una decisión",
    brick2: "Paquete de documentos",
    brick2sub: "Listas · formularios oficiales · usted presenta",
    brick3: "Quién es real y quién es estafa",
    brick3sub: "Puertas oficiales · banderas rojas",
    brick4: "Calor y visita perdida",
    brick4sub: "Stay Cool · 311 · 211",
    mini211: "Nevada 211",
    miniAccess: "ACCESS Nevada",
    miniDhcpf: "DHCFP PCS",
    miniCool: "Stay Cool Clark",
    navBoard: "Tablero",
    navWizard: "Asistente",
    navPack: "Paquete",
    navDirectory: "Directorio",
    navHeat: "Calor",
    navLegal: "Legal",
    footerLegal: "Legal / qué no es esto",
    wizardTitle: "¿Puede Nevada pagar este cuidado?",
    wizardLead:
      "Esto es una señal, no una decisión de elegibilidad. Nada se sube. Nadie en Medicaid ve esta pantalla.",
    stepWhere: "¿Dónde está la persona que necesita ayuda?",
    whereVegas: "Las Vegas / Condado Clark",
    whereNv: "En otra parte de Nevada",
    whereOut: "Fuera de Nevada",
    stepMedicaid: "¿Ya tiene Medicaid de Nevada?",
    medYes: "Sí",
    medNo: "No / no creo",
    medUnsure: "No sé",
    stepNeed: "¿Qué tipo de ayuda se necesita en casa? (marque las que apliquen)",
    needBath: "Bañarse o vestirse",
    needToilet: "Baño o incontinencia",
    needMeal: "Comidas o alimentación",
    needMove: "Entrar/salir de la cama o una silla",
    needMeds: "Recordar medicamentos (no enfermería)",
    needNone: "Sobre todo compañía / mandados",
    stepWho: "¿Quién sería el cuidador pagado, si hay alguno?",
    whoSelf: "La misma persona (sin ayudante pagado)",
    whoSpouse: "Cónyuge / pareja",
    whoParentMinor: "Padre o madre de un menor de 18",
    whoGuardian: "Tutor legal de la persona",
    whoAdultChild: "Hijo adulto, hermano u otro pariente (no cónyuge/tutor)",
    whoFriend: "Amigo / vecino / no pariente",
    whoAgency: "Una agencia con licencia enviaría personal",
    whoUnsure: "Aún no sé",
    next: "Siguiente ladrillo",
    back: "Atrás",
    restart: "Empezar de nuevo",
    resultTitle: "Hacia dónde apuntan las reglas públicas",
    resultNotAdvice: "Esto no es una determinación. Un trabajador de ACCESS Nevada o DHCFP tiene que decir sí o no.",
    pathAccessTitle: "Puerta 1 — solicitar o revisar Medicaid",
    pathAccessBody:
      "Medicaid de Nevada (incluido MAABD para muchos adultos mayores y personas con discapacidad) suele ser el camino hacia Servicios de Cuidado Personal. Solicite o revise el estado solo en ACCESS Nevada. Los paquetes en papel se envían a DSS, PO Box 15400, Las Vegas, NV 89114.",
    pathPcsTitle: "Puerta 2 — Servicios de Cuidado Personal (PCS)",
    pathPcsBody:
      "Si ya tiene Medicaid de Nevada, un médico u otra fuente permitida puede pedir una evaluación de PCS. El número público de DHCFP para esa petición es 800-525-2395. El PCS de Nevada puede ser por agencia o autodirigido a través de una Organización de Servicios Intermediarios con licencia — no a través de este sitio.",
    pathCannotPayTitle: "Alto — esta persona probablemente no puede ser el ayudante pagado",
    pathCannotPayBody:
      "Los Servicios de Cuidado Personal de Medicaid de Nevada generalmente no pagan a una persona legalmente responsable: cónyuge, tutor legal o padre/madre de un menor. Los hijos adultos de receptores adultos y muchos otros parientes a menudo sí pueden contratarse en el modelo autodirigido — esa decisión es del ISO y de DHCFP, no nuestra.",
    pathOutTitle: "Este tablero es para Nevada",
    companionOnly:
      "La compañía y los mandados por sí solos generalmente no son Servicios de Cuidado Personal. El PCS se basa en bañarse, vestirse, ir al baño, comidas y transferencias — un trabajador del caso todavía tiene que decidir.",
    pathOutBody:
      "Otros estados tienen reglas distintas (el CDPAP de Nueva York no es el PCS de Nevada). Empiece en el portal oficial de Medicaid de ese estado, no aquí.",
    path211Title: "Siempre — Nevada 211 y ADSD",
    path211Body:
      "Aun sin Medicaid, el 211 puede orientar sobre comidas, respiro para cuidadores y servicios de envejecimiento. ADSD es la red estatal de envejecimiento — no un intermediario fiscal.",
    openAccess: "Abrir ACCESS Nevada",
    openApply: "Cómo solicitar (DSS)",
    openPcs: "Abrir página DHCFP PCS",
    open211: "Abrir Nevada 211 mayores",
    callPcs: "Petición de evaluación PCS",
    callDss: "Línea de ayuda DWSS / Medicaid",
    callVegas: "Distrito Medicaid Las Vegas",
    packTitle: "Paquete de documentos",
    packLead:
      "Solo una lista local. No guardamos sus papeles, no llenamos PDFs ni enviamos nada a Nevada. Imprima o capture esta lista. Presente usted mismo en ACCESS Nevada.",
    packMaabd: "Suele pedirse para MAABD / Medicaid para personas mayores o con discapacidad",
    packPcs: "Suele pedirse después para Servicios de Cuidado Personal",
    packDone: "Listo",
    packOpen: "Página oficial",
    resetChecks: "Borrar marcas locales",
    dirTitle: "Quién es real y quién es estafa",
    dirLead:
      "Use solo las puertas que Nevada publica. No listamos agencias privadas ni “licencias” que no podemos verificar. Si alguien llama en frío pidiendo su SSN para “inscribirlo en Medicaid,” cuelgue.",
    dirOfficial: "Puertas oficiales",
    dirFlags: "Banderas rojas — aléjese",
    dirCall: "Llamar",
    heatTitle: "Calor y una visita perdida",
    heatLead:
      "Esta es una tarjeta de seguridad, no un expediente médico ni un reloj EVV. Sin diagnósticos, sin listas de medicamentos, sin prueba de que un cuidador llegó.",
    heatStayCool: "Stay Cool del condado Clark",
    heat311: "Ayuda estilo 211 / 311 del condado",
    heatIfMissed: "Si un cuidador no llegó",
    heatIfMissedBody:
      "Llame a la agencia o ISO que lo emplea. Si la persona está en peligro inmediato por el calor, llame al 911. Para enfriamiento que no es emergencia y ayuda a mayores, use Stay Cool y Nevada 211. Confirme el horario del centro de enfriamiento el día que vaya — cambia.",
    heatCenters: "Lugares de enfriamiento que la gente menciona (confirme horarios)",
    confirmHours: "Confirme el horario antes de ir",
    legalTitle: "Qué no es Free Care",
    legalBody:
      "Free Care es un navegador público para gente en el condado Clark y el resto de Nevada. No es FreedomCare, no es una Organización de Servicios Intermediarios con licencia, no es un intermediario fiscal, no es Medicaid y no es un empleador. El pago instantáneo a cuidadores, el EVV y las hojas de horas pertenecen a agencias e ISOs con licencia después de que el estado diga que alguien es elegible — nunca a este tablero de ladrillos.",
  },
};
