export const categories = [
  { id: "family", label: "Hire family", blurb: "A daughter, cousin, or neighbor — paid.", icon: "♡" },
  { id: "personal", label: "Personal care", blurb: "Bathing, dressing, transfers.", icon: "◈" },
  { id: "meals", label: "Meals & home", blurb: "Cooking, laundry, light house.", icon: "◉" },
  { id: "meds", label: "Meds & nursing", blurb: "Reminders, vitals, post-op.", icon: "✚" },
  { id: "companion", label: "Companionship", blurb: "Errands, walks, company.", icon: "○" },
  { id: "overnight", label: "Overnight", blurb: "Live-in and night shifts.", icon: "☾" },
];

export const menuItems = [
  { id: "adl", name: "Morning ADLs", desc: "Bathing, dressing, grooming, transfers", minutes: 120, price: 42, tags: ["personal", "family"] },
  { id: "meals", name: "Meals & kitchen", desc: "Shop, cook, feed, wash up", minutes: 90, price: 32, tags: ["meals", "family"] },
  { id: "meds", name: "Medication pass", desc: "Reminders, packaging check, vitals", minutes: 45, price: 22, tags: ["meds"] },
  { id: "companion", name: "Companion block", desc: "Walks, errands, conversation", minutes: 180, price: 48, tags: ["companion", "family"] },
  { id: "house", name: "Light housekeeping", desc: "Laundry, beds, tidy, trash", minutes: 90, price: 28, tags: ["meals"] },
  { id: "overnight", name: "Overnight watch", desc: "10pm–6am safety and toileting", minutes: 480, price: 168, tags: ["overnight"] },
  { id: "postop", name: "Post-hospital week", desc: "Wound-aware help the first 7 days home", minutes: 240, price: 96, tags: ["meds", "personal"] },
];

export const caregivers = [
  {
    id: "amina",
    name: "Amina Diallo",
    neighborhood: "Harlem",
    miles: 1.1,
    eta: 18,
    rating: 4.97,
    reviews: 412,
    rate: 24,
    creds: "HHA · 9 yrs",
    languages: ["English", "Wolof", "French"],
    tags: ["family", "personal", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Medicaid covers 100%",
    bio: "Daughter-care specialist. Cooks West African and American breakfasts, unhurried bathing, knows how to talk a stubborn father into his pills.",
    palette: ["#c4491d", "#f3ead8", "#2f5d45"],
  },
  {
    id: "luis",
    name: "Luis Ortega",
    neighborhood: "Sunset Park",
    miles: 2.4,
    eta: 26,
    rating: 4.91,
    reviews: 288,
    rate: 22,
    creds: "PCA · 6 yrs",
    languages: ["Spanish", "English"],
    tags: ["personal", "meds"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Same-day start",
    bio: "Transfers and gait-belt work. Former warehouse lead who retrained after his abuela’s stroke. Calm in bathrooms, bilingual with families.",
    palette: ["#1f4b73", "#e8d7c0", "#c4491d"],
  },
  {
    id: "mei",
    name: "Mei Chen",
    neighborhood: "Flushing",
    miles: 4.8,
    eta: 34,
    rating: 4.99,
    reviews: 640,
    rate: 28,
    creds: "HHA · dementia",
    languages: ["Mandarin", "English", "Cantonese"],
    tags: ["overnight", "companion", "personal"],
    familyOk: false,
    instantPay: true,
    open: true,
    promo: "Nights available",
    bio: "Overnight dementia specialist. Sings while she folds laundry. Families keep her for years because sundowning gets quieter.",
    palette: ["#3d2b56", "#f0e6d4", "#d4a054"],
  },
  {
    id: "sarah",
    name: "Sarah Brennan, RN",
    neighborhood: "Park Slope",
    miles: 1.9,
    eta: 22,
    rating: 4.94,
    reviews: 191,
    rate: 38,
    creds: "RN · post-acute",
    languages: ["English"],
    tags: ["meds", "personal"],
    familyOk: false,
    instantPay: true,
    open: true,
    promo: "Hospital-to-home",
    bio: "Seven years on a med-surg floor. Now she meets discharges at the door: meds reconciled, wound photos, a real plan before the next clinic visit.",
    palette: ["#8e2f12", "#efe4d0", "#1a1612"],
  },
  {
    id: "jordan",
    name: "Jordan Blake",
    neighborhood: "Bed-Stuy",
    miles: 2.1,
    eta: 20,
    rating: 4.88,
    reviews: 156,
    rate: 20,
    creds: "Companion · 4 yrs",
    languages: ["English"],
    tags: ["companion", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Errands today",
    bio: "Walks, pharmacies, the good grocery on Fulton. Treats companionship like a craft, not filler hours.",
    palette: ["#2f5d45", "#f6efe3", "#c4491d"],
  },
  {
    id: "rosa",
    name: "Rosa Alvarez",
    neighborhood: "Washington Heights",
    miles: 3.2,
    eta: 28,
    rating: 5.0,
    reviews: 98,
    rate: 21,
    creds: "Family PCA",
    languages: ["Spanish", "English"],
    tags: ["family", "personal", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Hire your people",
    bio: "Cares for her mother-in-law and two neighbors on the same block. Proof that the Grubhub model in care is often just paying the person already in the kitchen.",
    palette: ["#b42318", "#f4e7d2", "#1f4b73"],
  },
  {
    id: "deshawn",
    name: "DeShawn Carter",
    neighborhood: "Jamaica",
    miles: 5.5,
    eta: 38,
    rating: 4.9,
    reviews: 221,
    rate: 23,
    creds: "PCA · mobility",
    languages: ["English"],
    tags: ["personal"],
    familyOk: true,
    instantPay: true,
    open: false,
    promo: "Opens 6am",
    bio: "Hoyer lifts, stairs, stubborn knees. Ex-MTA, still on time. Families book him for the heavy hours and keep a family member on the light ones.",
    palette: ["#1a1612", "#e7d9c3", "#d4a054"],
  },
  {
    id: "priya",
    name: "Priya Nair",
    neighborhood: "Jackson Heights",
    miles: 4.1,
    eta: 31,
    rating: 4.96,
    reviews: 307,
    rate: 25,
    creds: "HHA · diabetes",
    languages: ["Hindi", "English", "Malayalam"],
    tags: ["meds", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Carb-smart meals",
    bio: "Builds a week of meals around insulin timing. Quiet, precise, will argue with a takeout menu if the sodium is a problem.",
    palette: ["#9a3412", "#efe6d6", "#2f5d45"],
  },
  {
    id: "elena",
    name: "Elena Popescu",
    neighborhood: "Astoria",
    miles: 3.6,
    eta: 29,
    rating: 4.93,
    reviews: 174,
    rate: 26,
    creds: "Live-in · 11 yrs",
    languages: ["Romanian", "English", "Greek"],
    tags: ["overnight", "family", "personal"],
    familyOk: true,
    instantPay: false,
    open: true,
    promo: "Weekly live-in",
    bio: "Live-in week blocks. Keeps a house running like a small inn: meds, soup, overnight toileting, a report for the daughter in Chicago.",
    palette: ["#3f2e1e", "#f0e4cf", "#c4491d"],
  },
  {
    id: "marcus",
    name: "Marcus Hale",
    neighborhood: "Fordham",
    miles: 6.2,
    eta: 41,
    rating: 4.87,
    reviews: 133,
    rate: 22,
    creds: "HHA · veteran",
    languages: ["English"],
    tags: ["personal", "companion"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "VA-friendly",
    bio: "Army medic, then HHA. Good with men who do not want ‘help.’ Does the work without making a speech about it.",
    palette: ["#1f4b73", "#eadcc6", "#2f5d45"],
  },
  {
    id: "fatima",
    name: "Fatima Hassan",
    neighborhood: "Bay Ridge",
    miles: 7.0,
    eta: 44,
    rating: 4.95,
    reviews: 86,
    rate: 21,
    creds: "PCA · 5 yrs",
    languages: ["Arabic", "English"],
    tags: ["personal", "family", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Halal kitchen",
    bio: "Personal care with a halal kitchen and prayer-aware scheduling. Families hire her because she does not treat the house like a facility.",
    palette: ["#2f5d45", "#f3ead8", "#8e2f12"],
  },
  {
    id: "naomi",
    name: "Naomi Feldman",
    neighborhood: "Upper West Side",
    miles: 0.6,
    eta: 12,
    rating: 4.98,
    reviews: 54,
    rate: 27,
    creds: "Family · Shabbos-aware",
    languages: ["English", "Hebrew"],
    tags: ["family", "companion", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "12 min away",
    bio: "Already the person who shops for her aunt. Kindred is how that labor gets a timesheet and a same-day deposit instead of another unpaid Saturday.",
    palette: ["#6b2d5b", "#f6efe3", "#d4a054"],
  },
];

export const intel = {
  asOf: "August 18, 2026",
  subject: "FreedomCare (Freedom Care LLC)",
  oneLiner:
    "A Medicaid-funded home-care platform that lets eligible people hire family or friends, then runs payroll, EVV, and instant pay — Grubhub’s two-sided marketplace, with the state as the card on file.",
  snapshot: [
    { label: "Years in business", value: "10 yrs 8 mo", note: "BBB: started 24 Dec 2015 · as of Aug 2026" },
    { label: "Legal entity", value: "Freedom Care LLC", note: "EIN 81-0913242 · DOS 4869472 · NPI 1922467554" },
    { label: "Staff (sworn)", value: "~260 NY", note: "Nov 2024 petition · ~30k NY CDPAP consumers then" },
    { label: "401(k) participants", value: "59,655", note: "Form 5500 · mostly PAs, not office staff" },
    { label: "Medicaid paid", value: "$3.03B", note: "2018–2024 claims · OpenMedicaid" },
    { label: "2024 run-rate", value: "$806M", note: "T1019 personal care, 15-min units" },
    { label: "Domain age", value: "21.5 yrs", note: "freedomcare.com created Jan 22, 2005" },
    { label: "States live", value: "15", note: "AZ CO CT GA IL IN MA MI MO NV NY OH OR PA WI" },
  ],
  people: {
    founderCeo: "Yoel Gabay",
    ceoSince: "April 2016 (LinkedIn). Entity started 24 Dec 2015 (BBB).",
    bbb: "A+ (BBB file 0121-165423). HQ page currently says not accredited; some location pages say accredited since 3 Feb 2017.",
    nyOperator: "Evergreenchoice, LLC d/b/a Freedomcare — NY LHCSA certificates 1957L001 (Jamaica, 11 Feb 2014), 1957L004 (Albany, 26 Nov 2024), 1957L003 (Suffern, 15 May 2026).",
    coo: "Corey Weiner",
    cfo: "Brett Labrie",
    hq: "1979 Marcus Avenue, Suite C115, North New Hyde Park, NY 11042",
    phone: "718.557.9526",
    email: "info@freedomcareny.com",
    type: "Privately held",
    linkedin: "https://www.linkedin.com/company/freedomcareco",
    offices: [
      "North New Hyde Park, NY (HQ)",
      "1700 Market Street, Suite 1005, Philadelphia, PA",
      "71 Raymond Rd, Suite 103, West Hartford, CT",
      "9465 Counselors Row, Suite 200, Indianapolis, IN",
      "429 Fourth Street, Suite 300, Pittsburgh, PA",
      "1301 Oak St, Suite 102, Kansas City, MO",
    ],
    footprint:
      "LinkedIn lists 14 U.S. offices and staff in 7 countries (US, Panama, Ukraine, UK, Singapore, Canada, Germany). ~692 of 702 LinkedIn-listed people are in the United States.",
  },
  employees: {
    caveat:
      "Public headcount mixes three populations: (1) corporate/ops staff, (2) certified aides employed by the LHCSA, (3) family caregivers on payroll. Treat any single number as a definition problem.",
    rows: [
      {
        source: "Nov 2024 Article 78 petition (verified)",
        date: "25 Nov 2024",
        figure: "~260 NY staff · ~30–35k NY consumers",
        includesCaregivers: "260 is direct NY staff. 30k/35k are consumers, not PAs.",
        url: "https://www.mcknightshomecare.com/wp-content/uploads/sites/10/2024/12/lawsuit-freedom-care.pdf",
        confidence: "High (company sworn pleading)",
      },
      {
        source: "Form 5500 401(k) (EIN 81-0913242)",
        date: "latest public filing in aggregators",
        figure: "59,655 plan participants",
        includesCaregivers: "Yes — this is the best public proxy for W-2 caregivers on payroll, not LinkedIn staff.",
        url: "https://form5500search.com/company/810913242",
        confidence: "High as a filed figure; year mix across filings",
      },
      {
        source: "LinkedIn company page",
        date: "Aug 2026",
        figure: "702 (501–1,000)",
        includesCaregivers: "Mostly staff. Job titles skew Medical/ops; caregiver salary bands exist but 702 is far too small to be the aide workforce.",
        url: "https://www.linkedin.com/company/freedomcareco",
        confidence: "High for LinkedIn-listed staff",
      },
      {
        source: "LeadIQ",
        date: "May–Jul 2026",
        figure: "~2,800 (1,001–5,000)",
        includesCaregivers: "Unknown methodology; likely broader than LinkedIn.",
        url: "https://leadiq.com/c/freedomcare/5a1da379230000530095a202",
        confidence: "Medium",
      },
      {
        source: "LinkedIn hiring posts",
        date: "Aug 2026",
        figure: "100+ open corp roles",
        includesCaregivers: "No — operations, nursing, sales ops.",
        url: "https://www.linkedin.com/posts/freedomcareco_were-hiring-activity-7492621050254364672-gV3i",
        confidence: "High",
      },
      {
        source: "IncFact company profile",
        date: "10 Aug 2026",
        figure: "Over 1,000 employees · revenue over $500M",
        includesCaregivers: "Unspecified. NAICS 6216. Modeled private-company estimate.",
        url: "https://incfact.com/company/freedomcare-lakesuccess-ny/",
        confidence: "Low–medium (not a filing)",
      },
      {
        source: "OpenMedicaid NPI 1922467554",
        date: "2018–2024",
        figure: "1.2M beneficiary rows / 22M claims",
        includesCaregivers: "Not employees. Volume implies a caregiver network orders of magnitude above staff headcount.",
        url: "https://www.openmedicaid.org/providers/1922467554",
        confidence: "High for paid claims; not a headcount",
      },
    ],
    estimate:
      "Best public range for corporate/ops staff in 2026 is ~500–1,200 (petition 260 NY in late 2024; LinkedIn 501–1,000; Lyons alleged a 500–600-person town hall then hundreds laid off after 1 Apr 2025). Caregiver payroll is a different number: Form 5500 shows ~60k plan participants at peak FI scale. After PPL, that NY book is gone.",
  },
  serp: {
    domain: "freedomcare.com",
    related: [
      "freedomcareny.com — created 28 Dec 2015, 301s to /new-york/",
      "myfreedomcare.com — 301s to freedomcare.com",
      "freedom.care — NOT owned; parked for sale",
      "app.freedomcare.com — does not resolve",
    ],
    title: "Hire a family member or friend to care for you | FreedomCare",
    meta: "FreedomCare allows people to choose who provides their care and the caregiver gets paid instantly after their shift.",
    sitelinks: [
      { label: "For Patients", href: "https://freedomcare.com/for-patients/" },
      { label: "For Caregivers", href: "https://freedomcare.com/for-caregivers/" },
      { label: "FAQs", href: "https://freedomcare.com/faqs/" },
      { label: "New York", href: "https://freedomcare.com/new-york/" },
      { label: "CDPAP guide", href: "https://freedomcare.com/blog/cdpap/" },
      { label: "Jobs", href: "https://freedomcare.com/jobs" },
    ],
    queries: [
      { q: "FreedomCare", intent: "Brand", note: "Homepage is the obvious #1; knowledge-style brand result." },
      { q: "Freedom Care", intent: "Brand misspelling", note: "Same property; also collides with unrelated UK/AU agencies." },
      { q: "CDPAP", intent: "Program", note: "Crowded NY SERP; FreedomCare competes with state .gov, PPL, and other FIs/LHCSAs." },
      { q: "get paid to care for family member medicaid", intent: "Non-brand demand", note: "This is the Grubhub keyword: convert existing unpaid labor into a paid shift." },
      { q: "InstaPay4Care", intent: "Product", note: "Brand for instant caregiver payout." },
    ],
    traffic: {
      hypestatRank: "#678,358 global",
      similarwebRank: "#191,416",
      semrushRank: "#30,318",
      dailyVisitors: "11.4k (HypeStat estimate)",
      monthlyVisits: "~345k SimilarWeb / ~386k SEMrush",
      organicKeywords: "45,904 in top 20 (SEMrush snippet)",
      organicTraffic: "67,968 (SEMrush snippet)",
      organicCost: "$505k AdWords equivalent",
      sources: "Direct 62% · Search 32% · Social 2.4% · Paid 2.3% · Referral 1.7%",
      device: "Mobile 80% / Desktop 20%",
      bounce: "72%",
      duration: "1:29",
      pagesPerVisit: "1.71",
      backlinks: "22,725 from 2,968 referring domains · authority score 39",
      host: "WordPress on WP Engine, Cloudflare in front (141.193.213.21)",
      cms: "WordPress (wp-json, WP Engine headers)",
    },
    whois: {
      created: "2005-01-22T14:15:20Z",
      updated: "2024-01-23",
      expires: "2026-01-22",
      registrar: "GoDaddy.com, LLC (IANA 146)",
      privacy: "Domains By Proxy, LLC",
      registryId: "140270539_DOMAIN_COM-VRSN",
      nameservers: ["ns09.domaincontrol.com", "ns10.domaincontrol.com"],
      note: "Domain is ~11 years older than the 2016 company. Treat domain age and company age as different clocks — they likely bought or reused the name.",
    },
  },
  apps: {
    ios: {
      name: "FreedomCare",
      id: "1175909593",
      url: "https://apps.apple.com/us/app/freedomcare/id1175909593",
      rating: "4.7 ★",
      ratings: "9.3k",
      version: "8.25.0 (Aug 7, 2026)",
      size: "175.4 MB",
      seller: "FreedomCare LLC",
    },
    android: {
      name: "FreedomCare",
      id: "com.freedomcare.freedomcareplus",
      url: "https://play.google.com/store/apps/details?id=com.freedomcare.freedomcareplus",
      reviews: "5.24k",
      downloads: "100k+",
      updated: "Aug 5, 2026",
      developerEmail: "zach@freedomcare.com",
    },
    patent: "U.S. Patent 10,740,728 — electronic timesheet / access verification, assigned to FreedomCare LLC, inventor Yoel Gabay",
    product:
      "Clock-in/out + EVV, timesheets, documents, paystubs, InstaPay4Care same-day payout to a Rapid Pay card. Reviews cluster on location/EVV failures and login loops — the operational heart of the Grubhub analog, and the fragile part.",
  },
  model: {
    analog:
      "Grubhub: hungry person opens app → picks a kitchen → order is dispatched → driver is paid. FreedomCare: Medicaid member (or family) opens funnel → picks a caregiver (often already in the house) → state authorizes hours → aide clocks a visit → Medicaid reimburses the agency → aide can be paid the same day.",
    breaks: [
      "The ‘customer’ does not pay. Medicaid / MLTC plans do. Conversion is eligibility + assessment, not a credit card.",
      "The ‘restaurant’ is frequently a relative, not a vendor acquiring new demand.",
      "Supply is licensed labor (HHA/PCA in NY LHCSA) plus family, not gig contractors.",
      "EVV and 15-minute billing codes (T1019) replace a delivery pin.",
      "NY 2025 killed the multi-FI CDPAP middle. The company bid for the statewide FI contract, lost to PPL, sued, lost again on appeal, and is not even a PPL facilitator. NY is now LHCSA PCS (certified aides), not a marketplace FI.",
    ],
    flow: [
      "Patient has Medicaid (Medicare alone does not qualify).",
      "Nurse assessment sets weekly hours.",
      "Patient chooses a caregiver — child, relative, friend; spouse rules vary by state.",
      "FreedomCare enrolls, trains/certifies (NY HHA/PCA via LHCSA), I-9, background.",
      "Caregiver clocks via app (location/EVV).",
      "Agency bills T1019 (personal care per 15 min) — 99% of $3.03B historical spend.",
      "InstaPay4Care can move wages the same day.",
    ],
    nyPivot:
      "FreedomCare bid for New York’s single statewide CDPAP FI contract and lost to Public Partnerships LLC (award 27 Sep 2024). It sued (Freedom Care LLC v NYSDOH); Supreme Court dismissed the Article 78 on 27 Mar 2025 and the First Department affirmed 21 Oct 2025. As of 1 Apr 2025 only PPL may FI CDPAP. FreedomCare is absent from PPL’s facilitator roster. The NY brand now sells LHCSA personal care via Evergreenchoice, LLC (certs 1957L001/003/004), with a CDPAP→LHCSA conversion funnel. LinkedIn shows 28 alumni at PPL. Other states still attach to local Medicaid family-care vehicles (ALTCS, HSP, CDS, SFC, AFC, Home Help).",
  },
  money: {
    yearly: [
      { year: 2018, paid: 95.8 },
      { year: 2019, paid: 169.2 },
      { year: 2020, paid: 276.9 },
      { year: 2021, paid: 379.7 },
      { year: 2022, paid: 539.5 },
      { year: 2023, paid: 758.8 },
      { year: 2024, paid: 805.9 },
    ],
    unit: "$ millions, Medicaid paid (OpenMedicaid, NPI 1922467554)",
    growth: "741% from first billing year through 2024",
    mix: "T1019 99.3% of spend · avg $137/claim vs $82 national median",
    patients: "LinkedIn: 162,000+ patients and caregivers served",
    reviews: "Company claims 8,000+ five-star reviews and 97% satisfaction",
  },
  timeline: [
    { year: "2005", event: "freedomcare.com registered at GoDaddy (Jan 22). Company does not yet exist." },
    { year: "2014", event: "Evergreenchoice, LLC LHCSA certificate 1957L001 opens in Jamaica, Queens (11 Feb)." },
    { year: "2015", event: "Freedom Care LLC starts/incorporates 24 Dec (BBB). ~10 years 8 months old as of 18 Aug 2026." },
    { year: "2016", event: "Public ‘founded 2016’ date. Yoel Gabay CEO from April. NPI 1922467554 enumerated 10 Feb. CDPAP FI play." },
    { year: "2016–17", event: "iOS app (bundle 1175909593) ships as electronic timesheets for CDPAP. BBB file opened Jan 2017." },
    { year: "2018", event: "Trademarks for FREEDOM CARE / FREEDOMCARE as participant-directed FI services. Medicaid billing hits $96M." },
    { year: "2020", event: "U.S. Patent 10,740,728 issues on computer-based access/timesheet verification." },
    { year: "2022–24", event: "Spend compounds to $540M then $759M then $806M. Multi-state expansion (MO, NV, PA, AZ, then SFC/AFC belt)." },
    { year: "Sep 2024", event: "PPL wins NY SFI RFP. FreedomCare sues; will lose at trial and on appeal (2025)." },
    { year: "Apr 2025", event: "PPL is the only legal CDPAP FI in NY. FreedomCare is not a facilitator. NY product becomes LHCSA PCS." },
    { year: "2025–26", event: "IL / MI / OH launches. Albany + Suffern LHCSA sites. Shell NPIs sit in CA, TX, KS, NH, MT, ME and others." },
  ],
  sources: [
    { name: "FreedomCare homepage", url: "https://freedomcare.com/" },
    { name: "FAQs / 15 states", url: "https://freedomcare.com/faqs/" },
    { name: "NY LHCSA positioning", url: "https://freedomcare.com/new-york/" },
    { name: "CDPAP 2026 guide (PPL pivot)", url: "https://freedomcare.com/blog/cdpap/" },
    { name: "CB Insights", url: "https://www.cbinsights.com/company/freedomcare" },
    { name: "OpenMedicaid NPI 1922467554", url: "https://www.openmedicaid.org/providers/1922467554" },
    { name: "NYS DOH CDPAP SFI", url: "https://health.ny.gov/facilities/long_term_care/reimbursement/cdpap/" },
    { name: "HypeStat / WHOIS / traffic", url: "https://hypestat.com/info/freedomcare.com" },
    { name: "App Store", url: "https://apps.apple.com/us/app/freedomcare/id1175909593" },
    { name: "Google Play", url: "https://play.google.com/store/apps/details?id=com.freedomcare.freedomcareplus" },
    { name: "LeadIQ", url: "https://leadiq.com/c/freedomcare/5a1da379230000530095a202" },
    { name: "BBB Freedom Care LLC", url: "https://www.bbb.org/us/ny/new-hyde-park/profile/home-health-care/freedom-care-llc-0121-165423" },
    { name: "IncFact profile", url: "https://incfact.com/company/freedomcare-lakesuccess-ny/" },
    { name: "Freedom Care LLC v NYSDOH", url: "https://caselaw.findlaw.com/court/ny-supreme-court-appellate-division/117848321.html" },
    { name: "NYS HFIS licenses", url: "https://health.data.ny.gov/Health/Health-Facility-General-Information/vn5v-hh5r" },
  ],
  states: [
    { code: "AZ", program: "ALTCS attendant care" },
    { code: "CO", program: "IHSS / CFC — not CDASS" },
    { code: "CT", program: "Adult Family Living" },
    { code: "GA", program: "Structured Family Caregiving" },
    { code: "IL", program: "Home Services Program (FI-like)" },
    { code: "IN", program: "Structured Family Caregiving" },
    { code: "MA", program: "Adult Foster Care" },
    { code: "MI", program: "Home Help" },
    { code: "MO", program: "Consumer Directed Services" },
    { code: "NV", program: "State-plan PCS (FI-like)" },
    { code: "NY", program: "LHCSA PCA/HHA — not CDPAP" },
    { code: "OH", program: "PCS + SFC (Cleveland area)" },
    { code: "OR", program: "In-Home Care" },
    { code: "PA", program: "CHC Personal Assistance" },
    { code: "WI", program: "Claimed PCS; thin / sitemap omits" },
  ],
};
