export const categories = [
  { id: "family", label: "Hire family", blurb: "A daughter, cousin, or neighbor — paid.", icon: "♡" },
  { id: "personal", label: "Personal care", blurb: "Bathing, dressing, transfers.", icon: "◈" },
  { id: "meals", label: "Meals & home", blurb: "Cooking, laundry, light house.", icon: "◉" },
  { id: "meds", label: "Meds & nursing", blurb: "Reminders, vitals, post-op.", icon: "✚" },
  { id: "companion", label: "Companionship", blurb: "Errands, walks, company.", icon: "○" },
  { id: "overnight", label: "Overnight", blurb: "Live-in and night shifts.", icon: "☾" },
];

export const menuItems = [
  { id: "adl", name: "Morning ADLs", desc: "Bathing, dressing, grooming, transfers", minutes: 120, price: 42, tags: ["personal", "family"] },
  { id: "meals", name: "Meals & kitchen", desc: "Shop, cook, feed, wash up", minutes: 90, price: 32, tags: ["meals", "family"] },
  { id: "meds", name: "Medication pass", desc: "Reminders, packaging check, vitals", minutes: 45, price: 22, tags: ["meds"] },
  { id: "companion", name: "Companion block", desc: "Walks, errands, conversation", minutes: 180, price: 48, tags: ["companion", "family"] },
  { id: "house", name: "Light housekeeping", desc: "Laundry, beds, tidy, trash", minutes: 90, price: 28, tags: ["meals"] },
  { id: "overnight", name: "Overnight watch", desc: "10pm–6am safety and toileting", minutes: 480, price: 168, tags: ["overnight"] },
  { id: "postop", name: "Post-hospital week", desc: "Wound-aware help the first 7 days home", minutes: 240, price: 96, tags: ["meds", "personal"] },
];

export const caregivers = [
  {
    id: "amina",
    name: "Amina Diallo",
    neighborhood: "Harlem",
    miles: 1.1,
    eta: 18,
    rating: 4.97,
    reviews: 412,
    rate: 24,
    creds: "HHA · 9 yrs",
    languages: ["English", "Wolof", "French"],
    tags: ["family", "personal", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Medicaid covers 100%",
    bio: "Daughter-care specialist. Cooks West African and American breakfasts, unhurried bathing, knows how to talk a stubborn father into his pills.",
    palette: ["#c4491d", "#f3ead8", "#2f5d45"],
  },
  {
    id: "luis",
    name: "Luis Ortega",
    neighborhood: "Sunset Park",
    miles: 2.4,
    eta: 26,
    rating: 4.91,
    reviews: 288,
    rate: 22,
    creds: "PCA · 6 yrs",
    languages: ["Spanish", "English"],
    tags: ["personal", "meds"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Same-day start",
    bio: "Transfers and gait-belt work. Former warehouse lead who retrained after his abuela’s stroke. Calm in bathrooms, bilingual with families.",
    palette: ["#1f4b73", "#e8d7c0", "#c4491d"],
  },
  {
    id: "mei",
    name: "Mei Chen",
    neighborhood: "Flushing",
    miles: 4.8,
    eta: 34,
    rating: 4.99,
    reviews: 640,
    rate: 28,
    creds: "HHA · dementia",
    languages: ["Mandarin", "English", "Cantonese"],
    tags: ["overnight", "companion", "personal"],
    familyOk: false,
    instantPay: true,
    open: true,
    promo: "Nights available",
    bio: "Overnight dementia specialist. Sings while she folds laundry. Families keep her for years because sundowning gets quieter.",
    palette: ["#3d2b56", "#f0e6d4", "#d4a054"],
  },
  {
    id: "sarah",
    name: "Sarah Brennan, RN",
    neighborhood: "Park Slope",
    miles: 1.9,
    eta: 22,
    rating: 4.94,
    reviews: 191,
    rate: 38,
    creds: "RN · post-acute",
    languages: ["English"],
    tags: ["meds", "personal"],
    familyOk: false,
    instantPay: true,
    open: true,
    promo: "Hospital-to-home",
    bio: "Seven years on a med-surg floor. Now she meets discharges at the door: meds reconciled, wound photos, a real plan before the next clinic visit.",
    palette: ["#8e2f12", "#efe4d0", "#1a1612"],
  },
  {
    id: "jordan",
    name: "Jordan Blake",
    neighborhood: "Bed-Stuy",
    miles: 2.1,
    eta: 20,
    rating: 4.88,
    reviews: 156,
    rate: 20,
    creds: "Companion · 4 yrs",
    languages: ["English"],
    tags: ["companion", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Errands today",
    bio: "Walks, pharmacies, the good grocery on Fulton. Treats companionship like a craft, not filler hours.",
    palette: ["#2f5d45", "#f6efe3", "#c4491d"],
  },
  {
    id: "rosa",
    name: "Rosa Alvarez",
    neighborhood: "Washington Heights",
    miles: 3.2,
    eta: 28,
    rating: 5.0,
    reviews: 98,
    rate: 21,
    creds: "Family PCA",
    languages: ["Spanish", "English"],
    tags: ["family", "personal", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Hire your people",
    bio: "Cares for her mother-in-law and two neighbors on the same block. Proof that the Grubhub model in care is often just paying the person already in the kitchen.",
    palette: ["#b42318", "#f4e7d2", "#1f4b73"],
  },
  {
    id: "deshawn",
    name: "DeShawn Carter",
    neighborhood: "Jamaica",
    miles: 5.5,
    eta: 38,
    rating: 4.9,
    reviews: 221,
    rate: 23,
    creds: "PCA · mobility",
    languages: ["English"],
    tags: ["personal"],
    familyOk: true,
    instantPay: true,
    open: false,
    promo: "Opens 6am",
    bio: "Hoyer lifts, stairs, stubborn knees. Ex-MTA, still on time. Families book him for the heavy hours and keep a family member on the light ones.",
    palette: ["#1a1612", "#e7d9c3", "#d4a054"],
  },
  {
    id: "priya",
    name: "Priya Nair",
    neighborhood: "Jackson Heights",
    miles: 4.1,
    eta: 31,
    rating: 4.96,
    reviews: 307,
    rate: 25,
    creds: "HHA · diabetes",
    languages: ["Hindi", "English", "Malayalam"],
    tags: ["meds", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Carb-smart meals",
    bio: "Builds a week of meals around insulin timing. Quiet, precise, will argue with a takeout menu if the sodium is a problem.",
    palette: ["#9a3412", "#efe6d6", "#2f5d45"],
  },
  {
    id: "elena",
    name: "Elena Popescu",
    neighborhood: "Astoria",
    miles: 3.6,
    eta: 29,
    rating: 4.93,
    reviews: 174,
    rate: 26,
    creds: "Live-in · 11 yrs",
    languages: ["Romanian", "English", "Greek"],
    tags: ["overnight", "family", "personal"],
    familyOk: true,
    instantPay: false,
    open: true,
    promo: "Weekly live-in",
    bio: "Live-in week blocks. Keeps a house running like a small inn: meds, soup, overnight toileting, a report for the daughter in Chicago.",
    palette: ["#3f2e1e", "#f0e4cf", "#c4491d"],
  },
  {
    id: "marcus",
    name: "Marcus Hale",
    neighborhood: "Fordham",
    miles: 6.2,
    eta: 41,
    rating: 4.87,
    reviews: 133,
    rate: 22,
    creds: "HHA · veteran",
    languages: ["English"],
    tags: ["personal", "companion"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "VA-friendly",
    bio: "Army medic, then HHA. Good with men who do not want ‘help.’ Does the work without making a speech about it.",
    palette: ["#1f4b73", "#eadcc6", "#2f5d45"],
  },
  {
    id: "fatima",
    name: "Fatima Hassan",
    neighborhood: "Bay Ridge",
    miles: 7.0,
    eta: 44,
    rating: 4.95,
    reviews: 86,
    rate: 21,
    creds: "PCA · 5 yrs",
    languages: ["Arabic", "English"],
    tags: ["personal", "family", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "Halal kitchen",
    bio: "Personal care with a halal kitchen and prayer-aware scheduling. Families hire her because she does not treat the house like a facility.",
    palette: ["#2f5d45", "#f3ead8", "#8e2f12"],
  },
  {
    id: "naomi",
    name: "Naomi Feldman",
    neighborhood: "Upper West Side",
    miles: 0.6,
    eta: 12,
    rating: 4.98,
    reviews: 54,
    rate: 27,
    creds: "Family · Shabbos-aware",
    languages: ["English", "Hebrew"],
    tags: ["family", "companion", "meals"],
    familyOk: true,
    instantPay: true,
    open: true,
    promo: "12 min away",
    bio: "Already the person who shops for her aunt. Kindred is how that labor gets a timesheet and a same-day deposit instead of another unpaid Saturday.",
    palette: ["#6b2d5b", "#f6efe3", "#d4a054"],
  },
];

export const intel = {
  asOf: "August 18, 2026",
  subject: "FreedomCare (Freedom Care LLC)",
  oneLiner:
    "A Medicaid-funded home-care platform that lets eligible people hire family or friends, then runs payroll, EVV, and instant pay — Grubhub’s two-sided marketplace, with the state as the card on file.",
  snapshot: [
    { label: "Years in business", value: "10 yrs 4 mo", note: "Founded Apr 2016 · as of Aug 2026" },
    { label: "Legal entity", value: "Freedom Care LLC", note: "NPI 1922467554 · New Hyde Park, NY" },
    { label: "Staff (LinkedIn)", value: "702", note: "501–1,000 band · corporate/ops, not caregivers" },
    { label: "Staff (LeadIQ)", value: "~2.8k", note: "Jul 2026 scrape · 1,001–5,000 band" },
    { label: "Medicaid paid", value: "$3.03B", note: "2018–2024 claims · OpenMedicaid" },
    { label: "2024 run-rate", value: "$806M", note: "T1019 personal care, 15-min units" },
    { label: "Domain age", value: "21.5 yrs", note: "freedomcare.com created Jan 22, 2005" },
    { label: "States live", value: "15", note: "AZ CO CT GA IL IN MA MI MO NV NY OH OR PA WI" },
  ],
  people: {
    founderCeo: "Yoel Gabay",
    ceoSince: "April 2016",
    coo: "Corey Weiner",
    cfo: "Brett Labrie",
    hq: "1979 Marcus Avenue, Suite C115, North New Hyde Park, NY 11042",
    phone: "718.557.9526",
    email: "info@freedomcareny.com",
    type: "Privately held",
    linkedin: "https://www.linkedin.com/company/freedomcareco",
    offices: [
      "North New Hyde Park, NY (HQ)",
      "1700 Market Street, Suite 1005, Philadelphia, PA",
      "71 Raymond Rd, Suite 103, West Hartford, CT",
      "9465 Counselors Row, Suite 200, Indianapolis, IN",
      "429 Fourth Street, Suite 300, Pittsburgh, PA",
      "1301 Oak St, Suite 102, Kansas City, MO",
    ],
    footprint:
      "LinkedIn lists 14 U.S. offices and staff in 7 countries (US, Panama, Ukraine, UK, Singapore, Canada, Germany). ~692 of 702 LinkedIn-listed people are in the United States.",
  },
  employees: {
    caveat:
      "Public headcount mixes three populations: (1) corporate/ops staff, (2) certified aides employed by the LHCSA, (3) family caregivers on payroll. Treat any single number as a definition problem.",
    rows: [
      {
        source: "LinkedIn company page",
        date: "Aug 2026",
        figure: "702 (501–1,000)",
        includesCaregivers: "Mostly staff. Job titles skew Medical/ops; caregiver salary bands exist but 702 is far too small to be the aide workforce.",
        url: "https://www.linkedin.com/company/freedomcareco",
        confidence: "High for LinkedIn-listed staff",
      },
      {
        source: "LeadIQ",
        date: "May–Jul 2026",
        figure: "~2,800 (1,001–5,000)",
        includesCaregivers: "Unknown methodology; likely broader than LinkedIn.",
        url: "https://leadiq.com/c/freedomcare/5a1da379230000530095a202",
        confidence: "Medium",
      },
      {
        source: "LinkedIn hiring posts",
        date: "Aug 2026",
        figure: "100+ open corp roles",
        includesCaregivers: "No — operations, nursing, sales ops.",
        url: "https://www.linkedin.com/posts/freedomcareco_were-hiring-activity-7492621050254364672-gV3i",
        confidence: "High",
      },
      {
        source: "OpenMedicaid NPI 1922467554",
        date: "2018–2024",
        figure: "1.2M beneficiary rows / 22M claims",
        includesCaregivers: "Not employees. Volume implies a caregiver network orders of magnitude above staff headcount.",
        url: "https://www.openmedicaid.org/providers/1922467554",
        confidence: "High for paid claims; not a headcount",
      },
    ],
    estimate:
      "Best public range for corporate/ops staff in 2026 is 700–3,000 depending on vendor. The paid caregiver workforce is not disclosed; Medicaid claim volume is consistent with tens of thousands of active aides, not hundreds.",
  },
  serp: {
    domain: "freedomcare.com",
    related: ["freedomcareny.com (legacy NY brand/email)", "app listings under FreedomCare LLC"],
    title: "Hire a family member or friend to care for you | FreedomCare",
    meta: "FreedomCare allows people to choose who provides their care and the caregiver gets paid instantly after their shift.",
    sitelinks: [
      { label: "For Patients", href: "https://freedomcare.com/for-patients/" },
      { label: "For Caregivers", href: "https://freedomcare.com/for-caregivers/" },
      { label: "FAQs", href: "https://freedomcare.com/faqs/" },
      { label: "New York", href: "https://freedomcare.com/new-york/" },
      { label: "CDPAP guide", href: "https://freedomcare.com/blog/cdpap/" },
      { label: "Jobs", href: "https://freedomcare.com/jobs" },
    ],
    queries: [
      { q: "FreedomCare", intent: "Brand", note: "Homepage is the obvious #1; knowledge-style brand result." },
      { q: "Freedom Care", intent: "Brand misspelling", note: "Same property; also collides with unrelated UK/AU agencies." },
      { q: "CDPAP", intent: "Program", note: "Crowded NY SERP; FreedomCare competes with state .gov, PPL, and other FIs/LHCSAs." },
      { q: "get paid to care for family member medicaid", intent: "Non-brand demand", note: "This is the Grubhub keyword: convert existing unpaid labor into a paid shift." },
      { q: "InstaPay4Care", intent: "Product", note: "Brand for instant caregiver payout." },
    ],
    traffic: {
      hypestatRank: "#678,358 global",
      similarwebRank: "#191,416",
      semrushRank: "#30,318",
      dailyVisitors: "11.4k (HypeStat estimate)",
      monthlyVisits: "~345k SimilarWeb / ~386k SEMrush",
      organicKeywords: "45,904 in top 20 (SEMrush snippet)",
      organicTraffic: "67,968 (SEMrush snippet)",
      organicCost: "$505k AdWords equivalent",
      sources: "Direct 62% · Search 32% · Social 2.4% · Paid 2.3% · Referral 1.7%",
      device: "Mobile 80% / Desktop 20%",
      bounce: "72%",
      duration: "1:29",
      pagesPerVisit: "1.71",
      backlinks: "22,725 from 2,968 referring domains · authority score 39",
      host: "WordPress on WP Engine, Cloudflare in front (141.193.213.21)",
      cms: "WordPress (wp-json, WP Engine headers)",
    },
    whois: {
      created: "2005-01-22T14:15:20Z",
      updated: "2024-01-23",
      expires: "2026-01-22",
      registrar: "GoDaddy.com, LLC (IANA 146)",
      privacy: "Domains By Proxy, LLC",
      registryId: "140270539_DOMAIN_COM-VRSN",
      nameservers: ["ns09.domaincontrol.com", "ns10.domaincontrol.com"],
      note: "Domain is ~11 years older than the 2016 company. Treat domain age and company age as different clocks — they likely bought or reused the name.",
    },
  },
  apps: {
    ios: {
      name: "FreedomCare",
      id: "1175909593",
      url: "https://apps.apple.com/us/app/freedomcare/id1175909593",
      rating: "4.7 ★",
      ratings: "9.3k",
      version: "8.25.0 (Aug 7, 2026)",
      size: "175.4 MB",
      seller: "FreedomCare LLC",
    },
    android: {
      name: "FreedomCare",
      id: "com.freedomcare.freedomcareplus",
      url: "https://play.google.com/store/apps/details?id=com.freedomcare.freedomcareplus",
      reviews: "5.24k",
      downloads: "100k+",
      updated: "Aug 5, 2026",
      developerEmail: "zach@freedomcare.com",
    },
    patent: "U.S. Patent 10,740,728 — electronic timesheet / access verification, assigned to FreedomCare LLC, inventor Yoel Gabay",
    product:
      "Clock-in/out + EVV, timesheets, documents, paystubs, InstaPay4Care same-day payout to a Rapid Pay card. Reviews cluster on location/EVV failures and login loops — the operational heart of the Grubhub analog, and the fragile part.",
  },
  model: {
    analog:
      "Grubhub: hungry person opens app → picks a kitchen → order is dispatched → driver is paid. FreedomCare: Medicaid member (or family) opens funnel → picks a caregiver (often already in the house) → state authorizes hours → aide clocks a visit → Medicaid reimburses the agency → aide can be paid the same day.",
    breaks: [
      "The ‘customer’ does not pay. Medicaid / MLTC plans do. Conversion is eligibility + assessment, not a credit card.",
      "The ‘restaurant’ is frequently a relative, not a vendor acquiring new demand.",
      "Supply is licensed labor (HHA/PCA in NY LHCSA) plus family, not gig contractors.",
      "EVV and 15-minute billing codes (T1019) replace a delivery pin.",
      "NY 2025 killed the multi-FI CDPAP middle. The company had to become a licensed agency (LHCSA) rather than a pure marketplace FI.",
    ],
    flow: [
      "Patient has Medicaid (Medicare alone does not qualify).",
      "Nurse assessment sets weekly hours.",
      "Patient chooses a caregiver — child, relative, friend; spouse rules vary by state.",
      "FreedomCare enrolls, trains/certifies (NY HHA/PCA via LHCSA), I-9, background.",
      "Caregiver clocks via app (location/EVV).",
      "Agency bills T1019 (personal care per 15 min) — 99% of $3.03B historical spend.",
      "InstaPay4Care can move wages the same day.",
    ],
    nyPivot:
      "Effective April 1, 2025, New York named Public Partnerships LLC (PPL) the sole statewide CDPAP fiscal intermediary, ending ~600 FIs. FreedomCare’s 2026 NY pages sell LHCSA personal care (certified aides, including trained family) as the alternative, while still running self-directed Medicaid programs in other states. LinkedIn even shows 28 alumni now at PPL — the talent followed the mandate.",
  },
  money: {
    yearly: [
      { year: 2018, paid: 95.8 },
      { year: 2019, paid: 169.2 },
      { year: 2020, paid: 276.9 },
      { year: 2021, paid: 379.7 },
      { year: 2022, paid: 539.5 },
      { year: 2023, paid: 758.8 },
      { year: 2024, paid: 805.9 },
    ],
    unit: "$ millions, Medicaid paid (OpenMedicaid, NPI 1922467554)",
    growth: "741% from first billing year through 2024",
    mix: "T1019 99.3% of spend · avg $137/claim vs $82 national median",
    patients: "LinkedIn: 162,000+ patients and caregivers served",
    reviews: "Company claims 8,000+ five-star reviews and 97% satisfaction",
  },
  timeline: [
    { year: "2005", event: "freedomcare.com registered at GoDaddy (Jan 22). Company does not yet exist." },
    { year: "2016", event: "FreedomCare founded; Yoel Gabay CEO from April. CDPAP fiscal-intermediary play in New York." },
    { year: "2016–17", event: "iOS app (bundle 1175909593) ships as electronic timesheets for CDPAP." },
    { year: "2018", event: "Medicaid billing visible at scale: $96M year one in the OpenMedicaid window." },
    { year: "2020", event: "U.S. Patent 10,740,728 issues on computer-based access/timesheet verification." },
    { year: "2022–24", event: "Spend compounds to $540M then $759M then $806M. Multi-state expansion." },
    { year: "2024", event: "NY budget names a single statewide FI. PPL wins the RFP." },
    { year: "Apr 2025", event: "PPL is the only legal CDPAP FI in NY. Former FIs must stop. FreedomCare leans on LHCSA PCA." },
    { year: "2025–26", event: "EIN press: Michigan Home Help, Illinois Home Services, Ohio Structured Family Caregiving. 15 states on the site." },
  ],
  sources: [
    { name: "FreedomCare homepage", url: "https://freedomcare.com/" },
    { name: "FAQs / 15 states", url: "https://freedomcare.com/faqs/" },
    { name: "NY LHCSA positioning", url: "https://freedomcare.com/new-york/" },
    { name: "CDPAP 2026 guide (PPL pivot)", url: "https://freedomcare.com/blog/cdpap/" },
    { name: "CB Insights", url: "https://www.cbinsights.com/company/freedomcare" },
    { name: "OpenMedicaid NPI 1922467554", url: "https://www.openmedicaid.org/providers/1922467554" },
    { name: "NYS DOH CDPAP SFI", url: "https://health.ny.gov/facilities/long_term_care/reimbursement/cdpap/" },
    { name: "HypeStat / WHOIS / traffic", url: "https://hypestat.com/info/freedomcare.com" },
    { name: "App Store", url: "https://apps.apple.com/us/app/freedomcare/id1175909593" },
    { name: "Google Play", url: "https://play.google.com/store/apps/details?id=com.freedomcare.freedomcareplus" },
    { name: "LeadIQ", url: "https://leadiq.com/c/freedomcare/5a1da379230000530095a202" },
  ],
};
